export type Vehicle = {
  id: string;
  plate: string;
  plateEnding: string;
  make: string;
  model: string;
  year: number;
  modelYear: number;
  color: string;
  doors: number;
  fuel: string;
  transmission: string;
  mileage: number;
  price: number;
  description?: string;
  status: 'available' | 'sold' | 'unavailable';
  images?: string[];
  featuredImage?: string;
};

export const vehicles: Vehicle[] = [
  {
    id: '1',
    plate: 'BRA2E19',
    plateEnding: '9',
    make: 'Volkswagen',
    model: 'Golf Highline 1.4 TSI',
    year: 2021,
    modelYear: 2021,
    color: 'Prata',
    doors: 4,
    fuel: 'Gasolina',
    transmission: 'Automático',
    mileage: 15000,
    price: 120000,
    description: 'Carro em excelente estado, único dono. Todas as revisões feitas na concessionária. Versão Highline com teto solar e painel digital.',
    status: 'available',
    images: ['https://picsum.photos/seed/car1/800/600', 'https://picsum.photos/seed/car-interior1/800/600', 'https://picsum.photos/seed/car-detail1/800/600'],
    featuredImage: 'https://picsum.photos/seed/car1/800/600',
  },
  {
    id: '2',
    plate: 'ABC1234',
    plateEnding: '4',
    make: 'Chevrolet',
    model: 'Onix LTZ 1.0 Turbo',
    year: 2022,
    modelYear: 2022,
    color: 'Branco',
    doors: 4,
    fuel: 'Flex',
    transmission: 'Automático',
    mileage: 5000,
    price: 85000,
    description: 'Praticamente novo, com baixa quilometragem. Versão LTZ, completo com multimídia MyLink e OnStar.',
    status: 'available',
    images: ['https://picsum.photos/seed/car2/800/600', 'https://picsum.photos/seed/car-interior2/800/600'],
    featuredImage: 'https://picsum.photos/seed/car2/800/600',
  },
  {
    id: '3',
    plate: 'XYZ5678',
    plateEnding: '8',
    make: 'Ford',
    model: 'Mustang GT Premium 5.0 V8',
    year: 2020,
    modelYear: 2020,
    color: 'Preto',
    doors: 2,
    fuel: 'Gasolina',
    transmission: 'Automático',
    mileage: 25000,
    price: 350000,
    description: 'Ícone americano em sua melhor forma. Motor V8 potente e ronco inconfundível. Cuidado com extremo zelo.',
    status: 'sold',
    images: ['https://picsum.photos/seed/car3/800/600'],
    featuredImage: 'https://picsum.photos/seed/car3/800/600',
  },
  {
    id: '4',
    plate: 'JKL4321',
    plateEnding: '1',
    make: 'Honda',
    model: 'Civic Touring 1.5 Turbo',
    year: 2019,
    modelYear: 2019,
    color: 'Cinza',
    doors: 4,
    fuel: 'Gasolina',
    transmission: 'Automático',
    mileage: 45000,
    price: 110000,
    description: 'Confiabilidade japonesa com design esportivo. Versão Touring com motor turbo. Ótimo para a cidade e estrada.',
    status: 'available',
    images: ['https://picsum.photos/seed/car4/800/600'],
    featuredImage: 'https://picsum.photos/seed/car4/800/600',
  },
  {
    id: '5',
    plate: 'MNO9876',
    plateEnding: '6',
    make: 'Toyota',
    model: 'Corolla Altis Hybrid 1.8',
    year: 2023,
    modelYear: 2023,
    color: 'Branco',
    doors: 4,
    fuel: 'Híbrido',
    transmission: 'CVT',
    mileage: 1000,
    price: 150000,
    description: 'O sedan mais vendido do Brasil, agora em sua versão híbrida. Economia e tecnologia de ponta. Cheira a novo.',
    status: 'available',
    images: ['https://picsum.photos/seed/car5/800/600'],
    featuredImage: 'https://picsum.photos/seed/car5/800/600',
  },
  {
    id: '6',
    plate: 'PQR6543',
    plateEnding: '3',
    make: 'Fiat',
    model: 'Toro Volcano 2.0 Diesel 4x4',
    year: 2018,
    modelYear: 2018,
    color: 'Vermelho',
    doors: 4,
    fuel: 'Diesel',
    transmission: 'Automático',
    mileage: 80000,
    price: 95000,
    description: 'Picape versátil e robusta. Versão Volcano com motor diesel e tração 4x4. Ideal para trabalho e lazer.',
    status: 'unavailable',
    images: ['https://picsum.photos/seed/car6/800/600'],
    featuredImage: 'https://picsum.photos/seed/car6/800/600',
  },
  {
    id: '7',
    plate: 'STU3210',
    plateEnding: '0',
    make: 'Jeep',
    model: 'Renegade Longitude 1.3 Turbo',
    year: 2022,
    modelYear: 2022,
    color: 'Prata',
    doors: 4,
    fuel: 'Flex',
    transmission: 'Automático',
    mileage: 12000,
    price: 130000,
    description: 'SUV compacto e valente. Versão Longitude com motor turbo flex. Ótimo estado de conservação.',
    status: 'available',
    images: ['https://picsum.photos/seed/car7/800/600'],
    featuredImage: 'https://picsum.photos/seed/car7/800/600',
  },
];
